---

- name: Create service account for application
  user: name=chunker
        system=yes
        home=/var/lib/chunker
        shell=/bin/false
        state=present

- name: Add Vagrant user to the chunker group
  user: name=vagrant
        append=yes
        group=chunker
        state=present
  when: developing

- name: Add Ubuntu user to the chunker group
  user: name=ubuntu
        append=yes
        group=chunker
        state=present
  when: packing

- name: Create configuration file directory
  file: path={{ chunker_env_dir }}
        owner=root
        group=chunker
        mode=0750
        state=directory

- name: Configure application
  copy: content={{ item.content }}
        dest={{ chunker_env_dir }}/{{ item.file }}
        owner=root
        group=chunker
        mode=0750
  with_items: chunker_config
  notify:
    - Restart chunker

- name: Configure service definition
  template: src=chunker.conf.j2 dest=/etc/init/chunker.conf
  notify:
    - Restart chunker

- name: Touch log file if it does not exist
  command: touch {{ chunker_log }}
           creates={{ chunker_log }}

- name: Set log file permissions
  file: path={{ chunker_log }} owner=chunker group=chunker mode=0644

- name: Configure Chunker log rotation
  template: src=logrotate-chunker.j2 dest=/etc/logrotate.d/chunker
